# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: 将项目打包为可执行程序

on:
  push:
    tags:
      - v*
jobs:
  create-release:
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}

  build-for-win:
    needs: create-release
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9.6"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run PyInstaller
        run: |
          python -m PyInstaller main.spec
      - name: Get Version
        shell: powershell
        id: get_version
        run: |
          $VERSION=(echo "${{ github.ref }}" | Select-String -Pattern 'v+[0-9]+(\.[0-9]+)*' | % { $_.Matches }) | % { $_.Value }
          echo $VERSION
          Write-Output "version=$VERSION" >> $env:GITHUB_OUTPUT
      - name: Create Zip
        run: |
          python -m zipfile -c automated-redemption-for-win.zip dist
      - name: Upload Release Asset
        id: upload_release_asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: automated-redemption-for-win.zip
          asset_name: automated-redemption-for-win.zip
          asset_content_type: application/zip

  build-for-linux:
    needs: create-release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run PyInstaller
        run: |
          python -m PyInstaller main.spec
      - name: Get Version
        id: get_version
        run: |
          VERSION=$(echo "${{ github.ref }}" | grep -oE 'v+[0-9]+(\.[0-9]+)*')
          echo ::set-output name=version::$VERSION
      - name: Print Upload Url
        run: |
          echo "${{ needs.create-release.outputs.upload_url }}"
      - name: Create Zip
        run: |
          python -m zipfile -c automated-redemption-for-linux.zip dist
      - name: Upload Release Asset
        id: upload_release_asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: automated-redemption-for-linux.zip
          asset_name: automated-redemption-for-linux.zip
          asset_content_type: application/zip

  build-for-mac:
    needs: create-release
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run PyInstaller
        run: |
          python -m PyInstaller main.spec
      - name: Get Version
        id: get_version
        run: |
          VERSION=$(echo "${{ github.ref }}" | grep -oE 'v+[0-9]+(\.[0-9]+)*')
          echo VERSION
          echo ::set-output name=version::$VERSION
      - name: Create Zip
        run: |
          python -m zipfile -c automated-redemption-for-mac.zip dist
      - name: Upload Release Asset
        id: upload_release_asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: automated-redemption-for-mac.zip
          asset_name: automated-redemption-for-mac.zip
          asset_content_type: application/zip